spring:
  profiles:
    active: local
  application:
    name: booking-system
  data:
    mongodb:
      uri: ${MONGO_URI}
  main:
    allow-bean-definition-overriding: true

  jackson:
    mapper:
      default-view-inclusion: false

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.data.mongodb: INFO

app:
  frontend:
    url: ${FRONTEND_URL:http://localhost:4200}

resend:
  api-key: ${RESEND_API_KEY}